name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copy Docs to Wiki Repo
        run: |
          mkdir -p wiki-temp
          cp -r docs/* wiki-temp
          mv .github $GITHUB_WORKSPACE/wiki-temp
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Update Wiki Repo
        run: |
          cd wiki-temp
          git init
          git add .
          git commit -m "Update Wiki from Code Repository"
          git push --force https://${{ secrets.WIKI_REPO_TOKEN }}@github.com/${{ secrets.WIKI_USERNAME }}/${{ secrets.WIKI_REPO }}.git main
        env:
          USERNAME: ${{ secrets.WIKI_USERNAME }}
          WIKI_REPO: ${{ secrets.WIKI_REPO }}
